services:
  db:
    image: postgres:latest
    container_name: testDB
    command: -p 1234
    expose:
      - 1234
    env_file:
      - .env-docker
    networks:
      - app-network

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    restart: always
    command: ["/bin/bash", "-c", "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"]
    ports:
      - 9999:8000
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network: